spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 100
  liquibase:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
springdoc:
  show-actuator: true
  api-docs:
    path: /api/docs
application:
  base-url: ${BASE_URL:/api}
logging:
  level:
    root: error
server:
  tomcat:
    threads:
      max: 200